# Generated by Django 5.2.15 on 2026-06-24 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_pms_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='airport_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_hobbies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_preferences',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, help_text='If set, billing is consolidated to this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_bookings', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reference_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='transport_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('CASH', 'Cash'), ('ONLINE', 'Online'), ('ONLINE_SSLCOMMERZ', 'Online (SSLCommerz)'), ('BANK_TRANSFER', 'Bank Transfer'), ('POS', 'POS Terminal')], default='ONLINE', max_length=50),
        ),
    ]
