# Generated by Django 5.2.15 on 2026-06-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_airport_details_booking_guest_hobbies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foliocharge',
            name='is_transferred',
            field=models.BooleanField(default=False, help_text='Flag if this charge was transferred to another folio'),
        ),
    ]
