# Generated by Django 5.2.15 on 2026-06-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_foliocharge_is_transferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_mode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='meal_plan',
            field=models.CharField(choices=[('EP', 'EP (European Plan - Room Only)'), ('CP', 'CP (Continental Plan - Room + Breakfast)'), ('MAP', 'MAP (Modified American Plan - Room + Breakfast + 1 Meal)'), ('AP', 'AP (American Plan - Room + 3 Meals)')], default='EP', max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_assigned',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
