# Generated by Django 5.2.15 on 2026-06-28 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_arrival_mode_booking_meal_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foliocharge',
            name='folio_window',
            field=models.PositiveSmallIntegerField(default=1, help_text='Folio window number (1-8)'),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='is_adjustment',
            field=models.BooleanField(default=False, help_text='True if this is an adjustment entry, not a primary charge'),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='reason_code',
            field=models.CharField(blank=True, default='', help_text='BILLING_ERROR | COMP | GOODWILL | MANAGER_APPROVAL | DUPLICATE | RATE_CORRECTION | OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='void_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='void_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='void_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
