# Generated by Django 5.2.15 on 2026-06-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_payment_settlement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='foliocharge',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='True when posted by Night Audit — prevents void/adjustment tampering'),
        ),
    ]
