# Generated by Django 5.2.15 on 2026-06-30 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_night_audit_production'),
        ('corporate', '0001_inventory_corporate_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='corporate_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='corporate.corporateaccount'),
        ),
    ]
