# Generated by Django 5.2.15 on 2026-06-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_housekeepingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='area_type',
            field=models.CharField(choices=[('ROOM', 'Room'), ('RESTAURANT', 'Restaurant'), ('BANQUET', 'Banquet'), ('PARKING', 'Parking'), ('ROOFTOP', 'Rooftop')], default='ROOM', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='is_public_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='housekeeping_status',
            field=models.CharField(choices=[('OC', 'Occupied Clean'), ('OD', 'Occupied Dirty'), ('VC', 'Vacant Clean'), ('VD', 'Vacant Dirty'), ('CO', 'Checkout'), ('ARR', 'Arrival')], default='VC', max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomtype'),
        ),
    ]
