# Generated by Django 6.0 on 2026-06-30 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_payment_settlement_fields'),
        ('rooms', '0005_breakfastlog_maintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastlog',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='The active booking for this breakfast (for meal plan tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast_logs', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='breakfastlog',
            name='meal_plan',
            field=models.CharField(blank=True, choices=[('EP', 'EP (Room Only)'), ('CP', 'CP (Room + Breakfast)'), ('MAP', 'MAP (Room + Breakfast + 1 Meal)'), ('AP', 'AP (Room + 3 Meals)')], default='', help_text='Meal plan from the booking (auto-filled on creation)', max_length=5),
        ),
        migrations.AddField(
            model_name='housekeepingtask',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='The guest stay that triggered this task (e.g. checkout clean)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks', to='bookings.booking'),
        ),
    ]
