# Generated by Django 5.2.15 on 2026-06-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_cms_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Icon class name e.g. MdRestaurant', max_length=100),
        ),
    ]
