# Generated by Django 5.2.15 on 2026-06-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_galleryimage_cms_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('faq', 'FAQ'), ('rooms', 'Rooms'), ('news', 'News'), ('contact', 'Contact')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/hero/')),
                ('meta_description', models.CharField(blank=True, help_text='For SEO purposes', max_length=255)),
                ('extra_content', models.JSONField(blank=True, default=dict, help_text='Dynamic section blocks')),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
            },
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Global Site Setting', 'verbose_name_plural': 'Global Site Settings'},
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='key',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='value',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='dark_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='light_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='Google Maps iframe src URL'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='name',
            field=models.CharField(default='Global Site Settings', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='Hotel Crown', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'facebook': 'url', 'twitter': 'url'}"),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
