# Generated by Django 5.2.15 on 2026-06-28 11:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_foliocharge_folio_window_foliocharge_is_adjustment_and_more'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='Crown Hotel', max_length=200)),
                ('business_date', models.DateField(default=datetime.date.today)),
                ('night_audit_pin', models.CharField(default='1234', help_text='PIN required to execute Night Audit', max_length=10)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='en', max_length=5)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Configuration',
                'verbose_name_plural': 'Hotel Configuration',
            },
        ),
        migrations.AddField(
            model_name='nightauditlog',
            name='am_occupied',
            field=models.PositiveIntegerField(default=0, help_text='AM (06:00) occupied rooms'),
        ),
        migrations.AddField(
            model_name='nightauditlog',
            name='evening_occupied',
            field=models.PositiveIntegerField(default=0, help_text='Evening (22:00) occupied rooms'),
        ),
        migrations.AddField(
            model_name='nightauditlog',
            name='pm_occupied',
            field=models.PositiveIntegerField(default=0, help_text='PM (14:00) occupied rooms'),
        ),
        migrations.CreateModel(
            name='FolioAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VOID', 'Void'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer Between Windows'), ('POST', 'Post Charge')], max_length=15)),
                ('reason_code', models.CharField(blank=True, choices=[('BILLING_ERROR', 'Billing Error'), ('COMP', 'Complimentary'), ('GOODWILL', 'Goodwill Gesture'), ('MANAGER_APPROVAL', 'Manager Approval'), ('DUPLICATE', 'Duplicate Entry'), ('RATE_CORRECTION', 'Rate Correction'), ('OTHER', 'Other')], default='', max_length=20)),
                ('reason_note', models.TextField(blank=True, default='')),
                ('from_window', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('to_window', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folio_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='bookings.foliocharge')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('room_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='1=Highest, 10=Lowest')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='bookings.booking')),
            ],
            options={
                'ordering': ['priority', 'queued_at'],
            },
        ),
        migrations.CreateModel(
            name='FolioWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_number', models.PositiveSmallIntegerField(default=1)),
                ('label', models.CharField(blank=True, default='', help_text='e.g. "Personal", "Corporate"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folio_windows', to='bookings.booking')),
            ],
            options={
                'ordering': ['window_number'],
                'unique_together': {('booking', 'window_number')},
            },
        ),
    ]
