# Generated by Django 5.2.15 on 2026-06-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_hotelconfig_nightauditlog_am_occupied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelconfig',
            name='manager_override_pin',
            field=models.CharField(default='5678', help_text='PIN to bypass overdue-checkout block during Night Audit', max_length=10),
        ),
        migrations.AddField(
            model_name='nightauditlog',
            name='service_charge_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='nightauditlog',
            name='tax_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
