# Generated by Django 5.2.15 on 2026-06-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpermission',
            name='module',
            field=models.CharField(choices=[('ROOMS', 'Rooms'), ('BOOKINGS', 'Bookings'), ('GUESTS', 'Guests'), ('RESTAURANT', 'Restaurant'), ('SPA', 'Spa'), ('CMS', 'CMS'), ('STAFF', 'Staff'), ('INVENTORY', 'Inventory'), ('CORPORATE', 'Corporate CRM')], max_length=20),
        ),
    ]
